### PR TITLE
Fix #229, a NBT hierarchy change

### LINKED ISSUE #229: ArmorEquipEvent exception
## Info

- Server version: Paper 1.13.1
- OldCombatMechanics version: Jenkins build 58
- Server log file: https://hastebin.com/okeculuzaw.cs
- OldCombatMechanics config file: default config

## Problem Description
Exception on armor equip event: https://hastebin.com/okeculuzaw.cs

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
## Problem

Starting with some newer 1.13 builds, the NBT hierarchy has changed. `NBTBase` used to be a *superclass* of `NBTTagCompound` and the comphenix class used this relationship to find the base class. Now `NBTTagCompound` *implements* the *interface* `NBTBase`, which makes the `getSuperclass` check performed return `Object`.
This causes the subsequent check for the `getTypeId` method to fail.

## Mitigation

The `NBTBase` class is now looked up via the Reflector mechanism already present in OCM. This mechanism directly resolves the runtime path of the NMS class and returns it, thus circumventing the checks.

## Closes
#229

## Other
It also adds a general exception handler catching every exception that arises during reloading a module. This prevents one bad module from screwing up the rest during reloading.

### CODE REVIEW

File: src/main/java/com/comphenix/example/NbtFactory.java [hunk 1]
```diff
@@ -50,7 +52,7 @@ private NbtFactory(){
 
                 // Prepare NBT
                 COMPOUND_CLASS = getMethod(0, Modifier.STATIC, offlinePlayer, "getData").getReturnType();
-                BASE_CLASS = COMPOUND_CLASS.getSuperclass();
+                BASE_CLASS = Reflector.getClass(ClassType.NMS, "NBTBase");
```
Comment (I-Al-Istannen) [inline src/main/java/com/comphenix/example/NbtFactory.java]: The class name seems to be stable since at least 1.8.8, so chances are high that it will remain that way. There wouldn't be much reason to change it unless they rework the whole NBT system or the maintainers change their mind on acronym capitalisation.

Comment (gvlfm78) [reply src/main/java/com/comphenix/example/NbtFactory.java]: So, because you're now looking it up using reflection, does this make it compatible with both 1.9 and 1.13?

Comment (I-Al-Istannen) [reply src/main/java/com/comphenix/example/NbtFactory.java]: It now uses a different way to look it up (by name, not by walking from a starting point (OfflinePlayer). The name is stable since at least 1.8.8, so yes.
